SistemaAC/Controllers/ActividadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaAC.Data;
using SistemaAC.Models;
using SistemaAC.ModelsClass;

namespace SistemaAC.Controllers
{
    public class ActividadesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ActividadesModels actividadesModels;

        public ActividadesController(ApplicationDbContext context)
        {
            _context = context;
            actividadesModels = new ActividadesModels(_context);
        }

        // GET: Actividades
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public List<object[]> filtrarDatos(int numPagina, string valor, string order)
        {
            return actividadesModels.filtrarDatos(numPagina, valor, order);
        }
        public List<Actividades> getActividades(int id)
        {
            return actividadesModels.getActividades(id);
        }
        [Authorize(Roles = "Administrador")]
        public List<IdentityError> editarActividad(int id, string nombre, string cantidad, string descripcion, Boolean estado, int funcion)
        {
            return actividadesModels.editarActividad(id, nombre, cantidad, descripcion, estado, funcion);
        }
        [Authorize(Roles = "Administrador")]
        public List<IdentityError> guardarActividad(string nombre, string cantidad, string descripcion, string estado)
        {
            return actividadesModels.guardarActividad(nombre, cantidad, descripcion, estado);
        }
        public List<Instructor> getInstructores()
        {
            return actividadesModels.getInstructores(); 
        }
        [Authorize(Roles = "Administrador")]
        public List<IdentityError> instructorActividad(List<Asignacion> asignacion)
        {
            return actividadesModels.instructorActividad(asignacion);
        }
    }
}

SistemaAC/Controllers/HorariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaAC.Data;
using SistemaAC.Models;
using SistemaAC.ModelsClass;

namespace SistemaAC.Controllers
{
    public class HorariosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private HorarioModels horarioModels;
        public HorariosController(ApplicationDbContext context)
        {
            _context = context;
            horarioModels = new HorarioModels(context);
        }

        // GET: Horarios
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public List<Actividades> getActividades()
        {
            return horarioModels.getActividades();
        }
        [Authorize(Roles = "Administrador")]
        public List<IdentityError> agregarHorario(int id, string dia, string hora, int actividad, string funcion)
        {
            return horarioModels.agregarHorario(id, dia, hora, actividad, funcion);
        }
        public List<object[]> filtrarHorario(int numPagina, string valor, string order)
        {
            return horarioModels.filtrarHorario(numPagina, valor, order);
        }
        public List<Horario> getHorario(int id)
        {
            return horarioModels.getHorario(id);
        }
        [Authorize(Roles = "Administrador")]
        public List<IdentityError> editarHorario(int id, string dia, string hora, int actividad, int funcion)
        {
            return horarioModels.editarHorario(id, dia, hora, actividad, funcion);
        }
        [Authorize(Roles = "Administrador")]
        public List<IdentityError> deleteHorario(int id)
        {
            return horarioModels.deleteHorario(id);
        }
    }
}

SistemaAC/Controllers/TarifasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaAC.Data;
using SistemaAC.Models;
using SistemaAC.ModelsClass;

namespace SistemaAC.Controllers
{
    public class TarifasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private TarifaModels tarifasModels;
        public TarifasController(ApplicationDbContext context)
        {
            _context = context;
            tarifasModels = new TarifaModels(context);
        }

        // GET: Tarifas
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public List<Actividades> getActividadesT()
        {
            return tarifasModels.getActividadesT();
        }
        [Authorize(Roles = "Administrador")]
        public List<IdentityError> agregarTarifa(int id, double valorEst, double valorEmp, double valorFam, double valorGrad, int actividad, string funcion)
        {
            return tarifasModels.agregarTarifa(id, valorEst, valorEmp, valorFam, valorGrad, actividad, funcion);
        }
        public List<object[]> filtrarTarifa(int numPagina, string valor, string order)
        {
            return tarifasModels.filtrarTarifa(numPagina, valor, order);
        }
        public List<Tarifas> getTarifas(int id)
        {
            return tarifasModels.getTarifas(id);
        }
        [Authorize(Roles = "Administrador")]
        public List<IdentityError> editarTarifa(int id, double valorEst, double valorEmp, double valorFam, double valorGrad, int actividad, int funcion)
        {
            return tarifasModels.editarTarifa(id, valorEst, valorEmp, valorFam, valorGrad, actividad, funcion);
        }
        [Authorize(Roles = "Administrador")]
        public List<IdentityError> deleteTarifa(int id)
        {
            return tarifasModels.deleteTarifa(id);
        }
    }
}

SistemaAC/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaAC.Data;
using SistemaAC.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace SistemaAC.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly ApplicationDbContext _context;
        UserManager<ApplicationUser> _userManager;
        RoleManager<IdentityRole> _roleManager;
        UsuarioRole _usuarioRole;
        public List<SelectListItem> usuarioRole;

        public UsuariosController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _usuarioRole = new UsuarioRole();
            usuarioRole = new List<SelectListItem>();
        }

        // GET: Usuarios
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Index()
        {
            var ID = "";
            List<Usuario> usuario = new List<Usuario>();
            var appUsuario = await _context.ApplicationUser.ToListAsync();
            foreach (var Data in appUsuario)
            {
                ID = Data.Id;
                usuarioRole = await _usuarioRole.GetRole(_userManager, _roleManager, ID);

                usuario.Add(new Usuario()
                {
                    Id = Data.Id,
                    UserName = Data.UserName,
                    PhoneNumber = Data.PhoneNumber,
                    Email = Data.Email,
                    Role = usuarioRole[0].Text

                });
            }
            return View(usuario.ToList());
            //return View(await _context.ApplicationUser.ToListAsync());
        }
        public async Task<List<Usuario>> GetUsuario(string id)
        {
            List<Usuario> usuario = new List<Usuario>();
            var appUsuario = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            usuarioRole = await _usuarioRole.GetRole(_userManager, _roleManager, id);

            usuario.Add(new Usuario()
            {
                Id = appUsuario.Id,
                UserName = appUsuario.UserName,
                PhoneNumber = appUsuario.PhoneNumber,
                Email = appUsuario.Email,
                Role = usuarioRole[0].Text,
                RoleId = usuarioRole[0].Value,
                AccessFailedCount = appUsuario.AccessFailedCount,
                ConcurrencyStamp = appUsuario.ConcurrencyStamp,
                EmailConfirmed = appUsuario.EmailConfirmed,
                LockoutEnabled = appUsuario.LockoutEnabled,
                LockoutEnd = appUsuario.LockoutEnd,
                NormalizedEmail = appUsuario.NormalizedEmail,
                NormalizedUserName = appUsuario.NormalizedUserName,
                PasswordHash = appUsuario.PasswordHash,
                PhoneNumberConfirmed = appUsuario.PhoneNumberConfirmed,
                SecurityStamp = appUsuario.SecurityStamp,
                TwoFactorEnabled = appUsuario.TwoFactorEnabled

            });
            return usuario;
        }

        public async Task<List<SelectListItem>> GetRoles()
        {
            List<SelectListItem> rolesLista = new List<SelectListItem>();

            rolesLista = _usuarioRole.Roles(_roleManager);

            return rolesLista;
        }

        public async Task<string> EditUsuario(string id, string userName, string email,
            string phoneNumber, int accessFailedCount, string concurrencyStamp, bool emailConfirmed,
            bool lockoutEnabled, DateTimeOffset lockoutEnd, string normalizedEmail, string normalizedUserName,
            string passwordHash, bool phoneNumberConfirmed, string securityStamp, bool twoFactorEnabled,
            string selectRole, ApplicationUser applicationUser)
        {
            var resp = "";
            try
            {
                applicationUser = new ApplicationUser
                {
                    Id = id,
                    UserName = userName,
                    Email = email,
                    PhoneNumber = phoneNumber,
                    EmailConfirmed = emailConfirmed,
                    LockoutEnabled = lockoutEnabled,
                    LockoutEnd = lockoutEnd,
                    NormalizedEmail = normalizedEmail,
                    NormalizedUserName = normalizedUserName,
                    PasswordHash = passwordHash,
                    PhoneNumberConfirmed = phoneNumberConfirmed,
                    SecurityStamp = securityStamp,
                    TwoFactorEnabled = twoFactorEnabled,
                    AccessFailedCount = accessFailedCount,
                    ConcurrencyStamp = concurrencyStamp
                };
                //Actualizamos los datos
                _context.Update(applicationUser);
                await _context.SaveChangesAsync();

                var usuario = await _userManager.FindByIdAsync(id);

                usuarioRole = await _usuarioRole.GetRole(_userManager, _roleManager, id);

                if (usuarioRole[0].Text != "No Role")
                {
                    await _userManager.RemoveFromRoleAsync(usuario, usuarioRole[0].Text);
                }

                if (selectRole == "No Role")
                {
                    selectRole = "Beneficiario";
                }

                var resultado = await _userManager.AddToRoleAsync(usuario, selectRole);

                resp = "Save";
            }
            catch
            {
                resp = "NoSave";
            }
            return resp;
        }

        public async Task<String> DeleteUsuario(string id)
        {
            var resp = "";
            try
            {
                var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
                _context.ApplicationUser.Remove(applicationUser);
                await _context.SaveChangesAsync();
                resp = "Delete";
            }
            catch
            {
                resp = "NoDelete";
            }
            return resp;
        }

        public async Task<String> CreateUsuario(string email,
                string phoneNumber, string passwordHash, string selectRole, ApplicationUser applicationUser)
        {
            var resp = "";
            applicationUser = new ApplicationUser
            {
                UserName = email,
                Email = email,
                PhoneNumber = phoneNumber
            };
            var result = await _userManager.CreateAsync(applicationUser, passwordHash);
            if (result.Succeeded)
            {
                await _userManager.AddToRoleAsync(applicationUser, selectRole);
                resp = "Save";
            }
            else
            {
                resp = "NoSave";
            }
            return resp;
        }

        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUser.Any(e => e.Id == id);
        }
    }
}

SistemaAC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de información gimnasio</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Navegación de palanca</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/U.png" alt="Visual Studio" class="img-responsive" /></a>
            </div>
            <div class="navbar-collapse ">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li><a asp-area="" asp-controller="Actividades" asp-action="Index">Actividades</a></li>
                    <li><a asp-area="" asp-controller="Horarios" asp-action="Index">Horarios</a></li>
                    <li><a asp-area="" asp-controller="Tarifas" asp-action="Index">Tarifas</a></li>
                    <li><a asp-area="" asp-controller="Maquinarias" asp-action="Index">Maquinaria</a></li>
                    <li><a asp-area="" asp-controller="Instructores" asp-action="Index">Instructores</a></li>
                    <li><a asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contáctenos</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Sistema De Información Gimnasio</p>
            <div>
                <ul>
                    <li><a href="/Actividades/">Actividades brindadas por el gimnasio</a></li>
                    <li><a href="/Horarios/">Horarios del gimnasio</a></li>
                    <li><a href="Maquinarias/">Maquinaria del gimnasio</a></li>
                    <li><a href="/Tarifas/">Tarifas del gimnasio</a></li>
                    <li><a href="/Instructores/">Instructores del gimnasio</a></li>
                    <li><a href="/Home/Contact/">Contactos</a></li>
                </ul>
            </div>
            <h6>Iconos realizados por Elegant Themes, monkik, Freepik, Icongeek26 y Smashicons en www.flaticon.com</h6>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/Actividades.js" asp-append-version="true"></script>
        <script src="~/js/Horarios.js" asp-append-version="true"></script>
        <script src="~/js/Maquinarias.js" asp-append-version="true"></script>
        <script src="~/js/Tarifas.js" asp-append-version="true"></script>
        <script src="~/js/Instructores.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>